"""Generate the cHI-MGNflow SAOI sweep: 8 arms, one per card 0-7.

    python configs/HI_MGNFlow/SAOI_sweep/gen_configs.py

THE DESIGN: a 2^3 FULL factorial -- section x learningr x capacity.

    Eight arms is exactly the full grid of three two-level factors, so nothing
    is confounded with anything. The previous SAOI grid was a 2^(4-1) half
    fraction whose two-factor effects came in confounded pairs; at eight arms
    for three factors that compromise is unnecessary.

      section     bot | top          the board's two halves, independent models
      learningr   1e-4 | 3e-4        cosine to 1e-8 over the whole run
      capacity    k0 | k1            128 / mp 4,6,8,6,4  |  192 / mp 6,8,12,8,6

WHY THESE THREE
    The earlier grid resolved its other two axes: `flow_t_sampling` uniform beat
    logit-normal by its largest margin (0.333) and batch 16 beat 32 (0.288).
    Both are fixed here at the winner.

    It could NOT resolve learningr (0.083) or capacity (0.074) -- and those two
    ties are the interesting part. A dead capacity axis sitting next to a live
    step-count axis is the signature of a run that could not train the model it
    had: a bigger network cannot show its capacity until it can be trained. The
    budget doubles here, which is the condition under which that ranking can
    invert. learningr is the other factor coupled to budget, since stretching a
    cosine changes which starting rate is right.

BUDGET
    2000 epochs at a MEASURED 113 s/epoch on one card -- the config's old
    500 s/epoch estimate was 4.4x pessimistic. That is ~63 h for a k0 arm.
    k1 costs roughly 1.5x per epoch, so those four arms land about a day later.
    The epoch count is held identical on purpose: a capacity comparison at a
    different budget answers a different question.

READ THE MIDDLE OF THE RUN
    cosine_T0 = epochs - warmup with eta_min 1e-8, so the learning rate is
    essentially zero by the last epoch and every curve flattens there whether
    or not the model converged. Convergence is decided by how much
    `det(1fwd) mse` improved through the MIDDLE of the run; the report
    computes that as a fraction and prints it.
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1] / 'campaigns'))

from sweep_common import write_sweep      # noqa: E402

OUT_ROOT = '../../output/chi-mgnflow/saoi_sweep'
EPOCHS = '2000'

K0 = {'latent_dim': ('128', 'capacity k0'),
      'mp_per_level': ('4, 6, 8, 6, 4', 'capacity k0')}
K1 = {'latent_dim': ('192', 'capacity k1 -- retested now the budget doubled'),
      'mp_per_level': ('6, 8, 12, 8, 6', 'capacity k1 -- ~1.5x per epoch')}

ARMS = []
_n = 0
for half in ('bot', 'top'):
    for lr, lr_tag in (('0.0001', 'lr1'), ('0.0003', 'lr3')):
        for cap, cap_tag in ((K0, 'k0'), (K1, 'k1')):
            _n += 1
            over = {'learningr': (lr, f'THE AXIS {lr_tag}')}
            over.update(cap)
            ARMS.append((str(_n), half, over, f'{half} {lr_tag} {cap_tag}'))

BANNER = """%   ============================================================
%   SAOI warpage, cHI-MGNflow -- arm {arm}   ({note})
%
%   section   {half}
{axis}
%   gpu {gpu} -- one arm per card, nothing shared
%
%   A 2^3 FULL factorial over section x learningr x capacity: eight arms is
%   exactly the full grid, so no effect is confounded with another. The grid's
%   other two axes are already resolved and fixed at their winners --
%   flow_t_sampling uniform (margin 0.333) and batch_size 16 (0.288).
%
%   GENERATED by gen_configs.py from ../SAOI_all_input/config_train_{half}.txt.
%   Do not hand-edit -- regenerate.
%   ============================================================
"""

INFER_BANNER = """%   ============================================================
%   SAOI inference -- arm {arm} ({note}), eval set {tag}.
%
%   `eval_dataset` is the `_compare_` file: the 125 realizations of the ONE
%   part in `infer_dataset`. That pairing is what makes sd_ratio's target 1.
%
%   A draw here is NOT one forward: it integrates the ODE, so it costs
%   flow_steps x 2 network evaluations under Heun.
%
%   gpu {gpu}. GENERATED by gen_configs.py -- do not hand-edit.
%   ============================================================
"""

SPEC = dict(
    here=HERE,
    prod_dir=HERE.parent / 'SAOI_all_input',
    out_root=OUT_ROOT,
    slug='chi-mgnflow',
    title='cHI-MGNflow SAOI sweep -- 2^3 full factorial, one card each:',
    banner=BANNER,
    infer_banner=INFER_BANNER,
    arms=ARMS,
    gpu_of=lambda arm: int(arm) - 1,          # arms 1..8 -> cards 0..7
    infer_sources={
        's26fe_main':    'config_infer_s26fe_main_{half}.txt',
        's26fe_sec':     'config_infer_s26fe_sec_{half}.txt',
        'sm_l345u_main': 'config_infer_sm_l345u_main_{half}.txt',
    },
    arch_keys={'latent_dim', 'mp_per_level'},
    train_fixed={
        'training_epochs': (EPOCHS,
                            'no resume exists and cosine_T0 = epochs - warmup, so '
                            'this is a COMPLETE run at its own schedule; '
                            '~113 s/epoch measured on one card at k0'),
        'batch_size': ('16', 'the grid measured b16 < b32 by 0.288'),
        'flow_t_sampling': ('uniform',
                            'RESOLVED: beat logit-normal by 0.333, the grid largest '
                            'margin. The SD3 result is image-domain and did not '
                            'predict this ordering'),
        'val_interval': ('50',
                         'each validation integrates the ODE (val_num_samples x '
                         'val_flow_steps x 2 forwards per graph) on ONE card while '
                         'nothing else runs -- the dominant non-training cost'),
        'test_interval': ('400', 'periodic plots'),
        'best_by': ('crps', 'select on the sampling metric, not the one-step loss'),
        'hierarchy_cache_keep': ('True',
                                 'REQUIRED: every arm shares one cache; a finishing '
                                 'arm must not delete it'),
        'num_vae_samples': ('200', 'draws per scene; unused in train mode'),
    },
    infer_fixed={
        'num_vae_samples': ('2000',
                            'draws per scene. One draw = flow_steps x 2 forwards, so '
                            'this stage costs arms x sets x draws x 60 evaluations'),
        'save_rollouts': ('False',
                          'the spread values still reach spread_values.npz; the '
                          'per-draw HDF5s would be tens of thousands of files'),
        'make_histogram': ('True', 'GT vs generated z_disp peak-to-valley'),
        'show_histogram': ('False', 'headless box: save the PNG, do not open a viewer'),
        'flow_steps': ('30', 'ODE steps per draw; sampling-time only'),
        'flow_solver': ('heun', '2nd-order trapezoid: 2 forwards per step'),
        'hierarchy_seed': ('0, 1, 2, 3',
                           'build one partition per seed and rotate across draw '
                           'batches, so one unlucky partition cannot poison a scene'),
    },
)

if __name__ == '__main__':
    write_sweep(SPEC)
