#!/usr/bin/env bash
# One-click runner for the cHI-MGNflow SAOI Wave B sweep.
#
# A 2^(4-1) RESOLUTION-IV HALF FRACTION: the fourth factor is D = A xor B xor C
# (defining relation I = ABCD). The 4 main effects are clean, but 2-factor
# effects come in CONFOUNDED PAIRS -- AB=CD, AC=BD, AD=BC -- so a large one
# cannot be attributed to a single pair without another run.
#
#   A  batch_size        b16 16 | b32 32
#   B  flow_t_sampling   tu  uniform | tl  logit-normal
#   C  capacity          k0  128 / mp 4,6,8,6,4 | k1  192 / mp 6,8,12,8,6
#   D  learningr         lr1 1e-4 | lr3 3e-4      GENERATED: D = A xor B xor C
#
# Arm names encode the cell: <b16|b32>_<tu|tl>_<k0|k1>_<lr1|lr3>. The files are
# config_train_<arm>.txt / config_infer_<arm>_<tag>.txt. Both are GENERATED by
# gen_sweep_configs.py -- do not hand-edit them, and do not hand-edit the arm
# list below either; it is printed verbatim by that script so the two can
# never drift. If you change gen_sweep_configs.py, re-paste its ARMS= line.
#
# EIGHT arms, ONE PER GPU (0-7) -- no card sharing, so there is real VRAM
# headroom and no OOM exposure from co-residency. Each arm pins its GPU in its
# own config (gpu_ids), so this script only launches them; it does not set
# CUDA_VISIBLE_DEVICES.
#
# Budget: 500 epochs at a measured 500 s/epoch is ~2.9 days per arm. This is a
# BUDGET-LIMITED comparison, NOT a converged one -- read the report that way,
# and see docs/SWEEP_PLAN.md (Wave 0) for why the budget is what it is.
#
# WATCH THE VRAM peak= LINE OF a b32_*_k1 ARM -- batch 32 at the wider/deeper
# capacity level is the worst corner, even with one arm per card.
#
# WATCH THE FIRST FEW EPOCHS' log line: Train fm=... | Valid fm=... | CRPS ...
# If CRPS is flat from the first val_interval on, the epoch budget is the
# problem, not the factors -- that is what Wave 0 exists to catch beforehand.
#
# THIS IS A MULTI-DAY RUN. Start it detached:
#   nohup bash configs/HI_MGNFlow/SAOI_sweepB/run_sweep.sh > sweep.out 2>&1 &
#   tail -f sweep.out
#   tail -f output/chi-mgnflow/saoi_sweepB/run_logs/1.log     # watch one arm
#
# Multiscale cache: none of the swept keys are part of the coarsening
# signature (voronoi_clusters is fixed, not an axis here), so all 8 arms hash
# to ONE cache file. An exclusive O_EXCL lock in
# general_modules/multiscale_cache.py lets exactly one process build it while
# the rest poll. Rather than have 7 jobs idle through a potentially hours-long
# build, this script launches ONE arm first and waits for the cache to appear
# before launching the rest -- and aborts the whole batch if that first arm
# dies, so a config error costs minutes, not days.
#
# DELETE ANY LEFTOVER CACHE BEFORE STARTING: cache_ready() only globs the file
# name, so a stale cache from a previous run makes this script skip the warm-up
# and launch all 8 straight into a cache MISS (the signature pins the source
# HDF5's mtime, which write_preprocessing_to_hdf5 bumps every run).
#
# The configs set hierarchy_cache_keep True so no finishing arm deletes the
# cache out from under the others. DELETE IT MANUALLY when the sweep is done:
#   rm dataset/SAOI/saoi_train_bot.mscache.*.h5
#
# Environment overrides:
#   PYTHON        interpreter (default: python)
#   LOG_ROOT      transcript directory (default: output/chi-mgnflow/saoi_sweepB/run_logs)
#   ARMS          space-separated arm names (default: all 8)
#   PREFLIGHT     1 = --check every arm before launching any (default); 0 = skip
#   TRAIN         1 = train (default). 0 = SKIP training and go straight to
#                 inference + scoring on checkpoints that already exist.
#   WARM_TIMEOUT  seconds to wait for the shared cache (default: 21600 = 6h)
#   INFER         1 = run each arm's inference configs after training (default)
#   INFER_TAGS    eval sets to infer (default: s26fe_main s26fe_sec sm_l345u_main)
#   SCORE         1 = run score_sweep.py when training ends (default); 0 = skip
#
# Usage:
#   bash configs/HI_MGNFlow/SAOI_sweepB/run_sweep.sh
#   ARMS="1 8" bash .../run_sweep.sh   # subset
#   PREFLIGHT=0 bash .../run_sweep.sh                          # skip validation
#   TRAIN=0 bash .../run_sweep.sh                              # infer + score only

# NOT `set -e`: per-arm failures are collected so one bad arm cannot kill the batch.
set -uo pipefail

PYTHON="${PYTHON:-python}"

# Every launch below redirects stdout to a log file, and Python block-buffers
# (~8 KB) when stdout is not a TTY. The effect is that an arm prints "Starting
# distributed training ..." and then the log sits dead for many minutes while
# the workers load the dataset and build the coarsening hierarchy -- it looks
# hung when it is fine. Unbuffer so `tail -f` reflects real progress; the
# per-line flush cost is nothing next to an epoch.
export PYTHONUNBUFFERED=1
PREFLIGHT="${PREFLIGHT:-1}"
TRAIN="${TRAIN:-1}"
WARM_TIMEOUT="${WARM_TIMEOUT:-21600}"
INFER="${INFER:-1}"
INFER_TAGS="${INFER_TAGS:-s26fe_main s26fe_sec sm_l345u_main}"
SCORE="${SCORE:-1}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$REPO_ROOT" || exit 1

# Absolute, derived from the script itself: the sweep folder can be renamed or
# copied for a wave C without editing anything here.
CFG_DIR="$SCRIPT_DIR"
LOG_ROOT="${LOG_ROOT:-output/chi-mgnflow/saoi_sweepB/run_logs}"
# Derived from the configs, NOT hardcoded. multiscale_cache.py writes the cache
# beside the dataset file as "<stem>.mscache.<digest>.h5", so the config's own
# dataset_dir is the only correct source. This was hardcoded once, and when the
# configs moved from dataset/saoi/ to dataset/SAOI/ it kept the old spelling --
# on Linux those are different directories, so cache_ready() stayed false, the
# warm-up never released, and seven of the eight arms never launched.
_first_cfg="$(ls "$CFG_DIR"/config_train_*.txt 2>/dev/null | head -1)"
if [ -n "$_first_cfg" ]; then
    # Config paths are relative to the method repo, i.e. '../../' reaches
    # REPO_ROOT -- which is already this script's cwd.
    _ds="$(sed -n 's/^dataset_dir[[:space:]]\{1,\}//p' "$_first_cfg" | head -1)"
    _ds="${_ds%%#*}"
    _ds="$(echo "$_ds" | sed 's/[[:space:]]*$//')"
    _ds="${_ds#../../}"
    CACHE_GLOB="${_ds%.h5}.mscache.*.h5"
else
    CACHE_GLOB="dataset/SAOI/saoi_train_bot.mscache.*.h5"
fi

# Must match gen_sweep_configs.arms() exactly -- it prints this line, so if the
# generator changes, re-paste its ARMS= output here rather than hand-editing.
DEFAULT_ARMS="1 2 3 4 5 6 7 8"
ARMS="${ARMS:-$DEFAULT_ARMS}"

mkdir -p "$LOG_ROOT"

cfg_for()     { echo "$CFG_DIR/config_train_${1}.txt"; }
inf_cfg_for() { echo "$CFG_DIR/config_infer_${1}_${2}.txt"; }
log_for()     { echo "$LOG_ROOT/${1}.log"; }
cache_ready() { compgen -G "$CACHE_GLOB" > /dev/null 2>&1; }

run_arm() {
    local arm=$1 cfg log rc
    cfg="$(cfg_for "$arm")"
    log="$(log_for "$arm")"
    if [ ! -f "$cfg" ]; then
        echo "[$arm] SKIP: config not found ($cfg)" >&2
        return 0
    fi
    # Capture the status directly. `$?` read after an `if` whose condition was
    # false and which has no else branch is the status of the *if statement*
    # (0), not of the command -- it always printed "exit 0" for a failed arm.
    "$PYTHON" AI_CAE4ALL_main.py --config "$cfg" > "$log" 2>&1
    rc=$?
    if [ "$rc" -eq 0 ]; then
        echo "[$arm] DONE"
        return 0
    fi
    echo "[$arm] FAILED (exit $rc) -- see $log" >&2
    return 1
}

echo "cHI-MGNflow Wave B -- 2^(4-1) resolution IV: batch x t-sched x capacity x lr"
echo "  REPO_ROOT = $REPO_ROOT"
echo "  PYTHON    = $PYTHON"
echo "  LOG_ROOT  = $LOG_ROOT"
echo "  ARMS      = $(echo "$ARMS" | wc -w) arms"
echo ""

# ---- Preflight every arm before committing GPU-days ------------------------
if [ "$PREFLIGHT" = "1" ]; then
    echo "Preflight (--check) on every arm..."
    pf_bad=0
    for arm in $ARMS; do
        cfg="$(cfg_for "$arm")"
        if [ ! -f "$cfg" ]; then
            echo "  $arm  MISSING CONFIG ($cfg)" >&2; pf_bad=1; continue
        fi
        if "$PYTHON" AI_CAE4ALL_main.py --config "$cfg" --check > "$LOG_ROOT/${arm}.check.log" 2>&1; then
            echo "  $arm  ok"
        else
            echo "  $arm  FAILED -- see $LOG_ROOT/${arm}.check.log" >&2; pf_bad=1
        fi
    done

    # Valid train configs say NOTHING about whether the histogram will have
    # ground truth. rollout.py skips it silently when `eval_dataset` is absent,
    # and draws against the wrong column when it points at the rollout's own
    # input instead of the `_compare_` file. Both have happened, neither raises,
    # and the sweep still reports a clean run. Catch it here -- before the
    # GPU-days, not on Monday morning.
    echo ""
    echo "Preflight (inference + histogram inputs)..."
    if ! "$PYTHON" "$CFG_DIR/check_eval_inputs.py"; then
        pf_bad=1
    fi

    if [ "$pf_bad" != "0" ]; then
        echo "" >&2
        echo "Preflight failed. Nothing launched. Fix the configs and re-run," >&2
        echo "or set PREFLIGHT=0 to launch anyway." >&2
        echo "If every arm reports MISSING CONFIG, the generated configs are" >&2
        echo "stale or absent -- regenerate them first:" >&2
        echo "  python configs/HI_MGNFlow/SAOI_sweepB/gen_sweep_configs.py" >&2
        exit 2
    fi
    echo "All arms validated."
    echo ""
fi

started=$(date +%s)
pids=(); names=()
rc=0

if [ "$TRAIN" != "1" ]; then
    echo "TRAIN=0 -- skipping training; using the checkpoints already on disk."
    echo "Arms with no checkpoint will fail their inference preflight and be"
    echo "reported, without stopping the rest."
    echo ""
else

# ---- Warm the shared multiscale cache with a single arm --------------------
# Word-split into an array: `cut -d' ' -f2-` echoes the WHOLE line back when it
# finds no delimiter, so a single-arm ARMS would have launched that one arm
# twice -- two jobs writing the same checkpoint and log.
read -r -a arm_list <<< "$ARMS"
first_arm="${arm_list[0]}"
rest_arms="${arm_list[*]:1}"

if cache_ready; then
    echo "Multiscale cache already present -- launching all arms at once."
    rest_arms="$ARMS"
else
    echo "Cold cache. Launching $first_arm alone to build it (timeout ${WARM_TIMEOUT}s)..."
    run_arm "$first_arm" & warm_pid=$!
    pids+=("$warm_pid"); names+=("$first_arm")

    deadline=$(( $(date +%s) + WARM_TIMEOUT ))
    while :; do
        if cache_ready; then
            echo "Cache is ready after $(( $(date +%s) - started ))s."
            break
        fi
        if ! kill -0 "$warm_pid" 2>/dev/null; then
            echo "" >&2
            echo "$first_arm exited before the cache appeared -- aborting the batch." >&2
            echo "See $(log_for "$first_arm")" >&2
            exit 3
        fi
        if [ "$(date +%s)" -ge "$deadline" ]; then
            echo "" >&2
            echo "Timed out waiting ${WARM_TIMEOUT}s for the cache. $first_arm is still" >&2
            echo "running (pid $warm_pid); raise WARM_TIMEOUT or launch the rest by hand." >&2
            exit 4
        fi
        sleep 30
    done
fi

# ---- Launch the remaining arms ---------------------------------------------
for arm in $rest_arms; do
    run_arm "$arm" &
    pids+=("$!"); names+=("$arm")
    echo "  launched $arm (pid $!)"
    sleep 3
done

echo ""
echo "$(echo "${names[*]}" | wc -w) arms running. Waiting..."

for k in "${!pids[@]}"; do
    if ! wait "${pids[$k]}"; then
        echo "${names[$k]} exited non-zero" >&2
        rc=1
    fi
done

ended=$(date +%s)
echo ""
echo "Training finished in $(( (ended - started) / 3600 ))h $(( ((ended - started) % 3600) / 60 ))m (rc=$rc)."

fi   # TRAIN
echo ""
echo "Transcripts : $LOG_ROOT/<arm>.log"
echo "Checkpoints : output/chi-mgnflow/saoi_sweepB/<arm>.pth"
echo ""

# ---- Inference: every arm against every held-out eval set -------------------
# One arm per GPU, so all 8 run concurrently; each arm's 3 eval sets run
# sequentially on the GPU it trained on. The generated configs set
# save_rollouts False: no trajectory HDF5s are written (scene x draws would be
# thousands of files across the grid). What each run leaves behind is
# histogram_compare.png and spread_values.npz -- the GT vs generated z_disp
# spread (max - min per realization) that score_sweep.py tabulates and
# overlays for all 8 arms on one axis.
#
# An arm whose training failed has no checkpoint; its inference preflights as
# a missing-input error, is logged, and does not stop the others.
run_infer_arm() {
    local arm=$1 tag cfg log rc=0 irc
    for tag in $INFER_TAGS; do
        cfg="$(inf_cfg_for "$arm" "$tag")"
        log="$LOG_ROOT/${arm}.infer_${tag}.log"
        if [ ! -f "$cfg" ]; then
            echo "[$arm/$tag] SKIP: no config ($cfg)" >&2
            continue
        fi
        "$PYTHON" AI_CAE4ALL_main.py --config "$cfg" > "$log" 2>&1
        irc=$?
        if [ "$irc" -ne 0 ]; then
            echo "[$arm/$tag] INFER FAILED (exit $irc) -- see $log" >&2
            rc=1
        fi
    done
    return $rc
}

if [ "$INFER" = "1" ]; then
    # Second gate: the checkpoints exist only now, so this is the first moment
    # the inference configs can be validated in full. Without it a bad infer
    # config is discovered after training has already been thrown away for the
    # night, with nobody watching.
    if [ "$PREFLIGHT" = "1" ]; then
        echo "Preflight (--check) on every inference config..."
        inf_bad=0
        for arm in $ARMS; do
            for tag in $INFER_TAGS; do
                icfg="$(inf_cfg_for "$arm" "$tag")"
                if [ ! -f "$icfg" ]; then
                    echo "  $arm/$tag  MISSING CONFIG ($icfg)" >&2; inf_bad=1; continue
                fi
                if ! "$PYTHON" AI_CAE4ALL_main.py --config "$icfg" --check                         > "$LOG_ROOT/${arm}.${tag}.check.log" 2>&1; then
                    echo "  $arm/$tag  FAILED -- see $LOG_ROOT/${arm}.${tag}.check.log" >&2
                    inf_bad=1
                fi
            done
        done
        if [ "$inf_bad" != "0" ]; then
            echo "" >&2
            echo "Inference preflight failed. No inference launched; the trained" >&2
            echo "checkpoints are untouched. Fix the configs and re-run with" >&2
            echo "  TRAIN=0 INFER=1 SCORE=1 bash $0" >&2
            exit 2
        fi
        echo "All inference configs validated."
        echo ""
    fi

    n_tags=$(echo "$INFER_TAGS" | wc -w)
    n_arms=$(echo "$ARMS" | wc -w)
    echo "Inference: $n_arms arms x $n_tags eval sets = $(( n_arms * n_tags )) runs."
    inf_started=$(date +%s)
    inf_pids=(); inf_names=()
    for arm in $ARMS; do
        run_infer_arm "$arm" &
        inf_pids+=("$!"); inf_names+=("$arm")
        sleep 2
    done
    for k in "${!inf_pids[@]}"; do
        if ! wait "${inf_pids[$k]}"; then
            echo "${inf_names[$k]}: at least one eval set failed" >&2
            rc=1
        fi
    done
    inf_ended=$(date +%s)
    echo "Inference finished in $(( (inf_ended - inf_started) / 60 ))m."
    echo "  Histograms : output/chi-mgnflow/saoi_sweepB/infer/<arm>/<tag>/histogram_compare.png"
    echo ""
else
    echo "INFER=0 -- skipped. The warpage table will be empty."
    echo ""
fi

# ---- Score the grid --------------------------------------------------------
# CRPS is the sampling-path score and the only training-time metric that
# mirrors what inference does; the warpage table (from the inference stage) is
# the physical quantity the sweep is actually for. Runs even when rc != 0 so a
# partially-failed batch still yields a report for the arms that did finish
# (score_sweep.py skips arms with no checkpoint).
REPORT="output/chi-mgnflow/saoi_sweepB/sweep_results.md"
if [ "$SCORE" = "1" ]; then
    echo "Scoring the grid..."
    if "$PYTHON" "$CFG_DIR/score_sweep.py" \
            --arms $ARMS \
            --python "$PYTHON" \
            --out-dir output/chi-mgnflow/saoi_sweepB \
            --run-logs "$LOG_ROOT" \
            > "$LOG_ROOT/score_sweep.log" 2>&1; then
        echo "Scoring complete."
    else
        echo "Scoring FAILED (exit $?) -- see $LOG_ROOT/score_sweep.log" >&2
        rc=1
    fi
    echo ""
    if [ -f "$REPORT" ]; then
        echo "================= RESULTS ================="
        cat "$REPORT"
        echo "==========================================="
        echo ""
        echo "Report   : $REPORT      <-- paste this file to Claude"
        echo "Raw JSON : output/chi-mgnflow/saoi_sweepB/sweep_results.json"
    fi
else
    echo "SCORE=0 -- skipped. Run it later with:"
    echo "  $PYTHON $CFG_DIR/score_sweep.py --run-logs $LOG_ROOT"
fi

echo ""
echo "THEN DELETE THE SHARED CACHE (configs set hierarchy_cache_keep True):"
echo "  rm $CACHE_GLOB"
exit $rc
