#!/usr/bin/env python3
"""Generate the full-resolution ex3 config matrix from checked-in ex2 templates.

Only the files listed in ``GENERATED`` are written.  The ex2 templates provide
each backend's live architecture keys; this script changes the dataset contract
to the reordered static NASA-CRM problem and applies method-specific sizing.
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TRAIN_DATA = "../dataset/ex3_train_reordered.h5"
TEST_DATA = "../dataset/ex3_test_reordered.h5"


def read_flat(path: Path) -> OrderedDict[str, str]:
    values: OrderedDict[str, str] = OrderedDict()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("%") or line == "'":
            continue
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            raise ValueError(f"{path}: malformed config line: {raw!r}")
        key, value = parts
        values[key.lower()] = value.strip()
    return values


def write_flat(path: Path, values: OrderedDict[str, str], description: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    width = max(len(key) for key in values)
    lines = [
        "% Generated by configs/ex3/generate_full_configs.py",
        f"% {description}",
        "% Dataset layout: xyz | Cp,Cf_x,Cf_y,Cf_z | 6 global conditions | normal_xyz,area",
        "",
    ]
    lines.extend(f"{key.ljust(width)}  {value}" for key, value in values.items())
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def set_common(
    values: OrderedDict[str, str],
    *,
    model: str,
    mode: str,
    checkpoint: str,
    rollout_dir: str,
    log_file: str | None = None,
) -> None:
    values["model"] = model
    values["mode"] = mode
    values["gpu_ids"] = "0"
    values["modelpath"] = checkpoint
    if log_file is not None:
        values["log_file_dir"] = log_file
    else:
        values.pop("log_file_dir", None)
    if mode == "train":
        values["dataset_dir"] = TRAIN_DATA
        values["infer_dataset"] = TEST_DATA
    else:
        values.pop("dataset_dir", None)
        values["infer_dataset"] = TEST_DATA
    values["inference_output_dir"] = rollout_dir
    values["infer_timesteps"] = "1"
    values["split_seed"] = "42"
    values["input_var"] = "4"
    values["output_var"] = "4"
    values["cond_var"] = "10"
    values["feature_loss_weights"] = "1.0, 1.0, 1.0, 1.0"
    values["use_node_types"] = "False"
    values["augment_geometry"] = "False"
    values["use_world_edges"] = "False"
    values["time_integration"] = "ar_ot"
    if mode == "train":
        values["training_epochs"] = "2000"
        values["batch_size"] = "1"
        values["test_batch_idx"] = "0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
        values["test_interval"] = "100"
        values["val_interval"] = "5"


def generate_meshgraphnets(
    *,
    hierarchical: bool,
    mode: str,
    variant: str = "as_is",
) -> tuple[Path, OrderedDict[str, str], str]:
    if not hierarchical and variant != "as_is":
        raise ValueError("flat MeshGraphNets does not accept an HI-MGN variant")
    if variant not in {"as_is", "p1", "p2", "p12"}:
        raise ValueError(f"unsupported HI-MGN variant: {variant}")

    kind = "meshgraphnets" if not hierarchical else (
        "himgn" if variant == "as_is" else f"himgn_{variant}"
    )
    source = ROOT / "configs" / "MeshGraphNets" / "ex2" / f"config_{'train' if mode == 'train' else 'infer'}_{kind}.txt"
    values = read_flat(source)
    checkpoint = f"../output/meshgraphnets/ex3/full/model_{kind}.pth"
    rollout = f"../output/meshgraphnets/rollout/ex3/full/{kind}"
    log = f"../../output/meshgraphnets/ex3/full/train_{kind}.log"
    set_common(
        values,
        model="meshgraphnets",
        mode=mode,
        checkpoint=checkpoint,
        rollout_dir=rollout,
        log_file=log if mode == "train" else None,
    )
    values["parallel_mode"] = "ddp"
    values["edge_var"] = "8"
    values["positional_features"] = "4"
    values["message_passing_num"] = "15"
    values["latent_dim"] = "128"
    values["use_checkpointing"] = "True"
    values["use_multiscale"] = "True" if hierarchical else "False"
    if hierarchical:
        values["coarsening_type"] = "voronoi_seedmean"
        values["voronoi_clusters"] = "5000, 100"
        values["multiscale_levels"] = "2"
        values["mp_per_level"] = "4, 6, 8, 6, 4"
        if variant in {"p1", "p12"}:
            values["pool_type"] = "attention"
            values["unpool_type"] = "attention"
            values["pool_heads"] = "4"
        else:
            values["pool_type"] = "mean"
            values["unpool_type"] = "sum"
            values.pop("pool_heads", None)
        values["voronoi_branches"] = "1, 4" if variant in {"p2", "p12"} else "1, 1"
    else:
        for key in (
            "coarsening_type", "voronoi_clusters", "multiscale_levels",
            "mp_per_level", "pool_type", "unpool_type", "pool_heads",
            "voronoi_branches",
        ):
            values.pop(key, None)
    file_mode = "train" if mode == "train" else "infer"
    destination = ROOT / "configs" / "MeshGraphNets" / "ex3" / f"config_{file_mode}_{kind}_full.txt"
    architecture = "flat MeshGraphNets" if not hierarchical else (
        "HI-MGN as-is" if variant == "as_is" else f"HI-MGN {variant.upper()}"
    )
    description = f"ex3 full-resolution {architecture} {mode} (static AR-OT path)"
    return destination, values, description


def generate_operator(model: str, mode: str) -> tuple[Path, OrderedDict[str, str], str]:
    source = ROOT / "configs" / "Neural_Operator" / "ex2" / f"config_{'train' if mode == 'train' else 'infer'}_{model}.txt"
    values = read_flat(source)
    checkpoint = f"../output/neural_operator/ex3/full/{model}.pth"
    rollout = f"../output/neural_operator/rollout/ex3/full/{model}"
    log = f"../../output/neural_operator/ex3/full/{model}.log"
    set_common(
        values,
        model=model,
        mode=mode,
        checkpoint=checkpoint,
        rollout_dir=rollout,
        log_file=log if mode == "train" else None,
    )
    values["parallel_mode"] = "ddp"
    values["positional_features"] = "4"
    values["operator_dim"] = "auto"
    values["global_condition_features"] = "none"
    values["write_preprocessing"] = "False"
    values["use_multiscale"] = "False"
    if model == "gino":
        values["gino_in_radius"] = "0.30"
        values["gino_out_radius"] = "0.30"
        values["gino_max_empty_input_fraction"] = "0.25"
        values["gino_query_chunk_size"] = "50000"
        values["gino_use_torch_cluster"] = "True"
    file_mode = "train" if mode == "train" else "infer"
    destination = ROOT / "configs" / "Neural_Operator" / "ex3" / f"config_{file_mode}_{model}_full.txt"
    return destination, values, f"ex3 full-resolution {model} {mode}"


def generate_transolver(mode: str) -> tuple[Path, OrderedDict[str, str], str]:
    source = ROOT / "configs" / "Transolver" / "ex2" / f"config_{'train' if mode == 'train' else 'infer'}_transolver.txt"
    values = read_flat(source)
    set_common(
        values,
        model="transolver",
        mode=mode,
        checkpoint="../output/transolver/ex3/full/transolver.pth",
        rollout_dir="../output/transolver/rollout/ex3/full/transolver",
        log_file="../../output/transolver/ex3/full/train_transolver.log" if mode == "train" else None,
    )
    values["parallel_mode"] = "ddp"
    values["positional_features"] = "4"
    values["attention_kernel"] = "slice_space"
    values["chunk_size"] = "8192"
    values["amortized_training"] = "True" if mode == "train" else "False"
    values["amortized_cache_nodes"] = "100000"
    values["amortized_query_nodes"] = "50000"
    values["infer_mode"] = "decoupled"
    values["infer_chunk_size"] = "65536"
    values["small_output_init"] = "False"
    values["use_checkpointing"] = "True"
    if mode == "train":
        values["num_layers"] = "24"
        values["slice_num"] = "64"
        values["mlp_ratio"] = "2"
        values["learningr"] = "0.001"
        values["weight_decay"] = "0.05"
        values["max_grad_norm"] = "1.0"
    values["write_preprocessing"] = "False"
    values["use_multiscale"] = "False"
    values.pop("test_batch_idx", None)
    file_mode = "train" if mode == "train" else "infer"
    destination = ROOT / "configs" / "Transolver" / "ex3" / f"config_{file_mode}_transolver_full.txt"
    return destination, values, f"ex3 full-resolution Transolver {mode}"


def simulgenvae_train() -> tuple[Path, OrderedDict[str, str], str]:
    values = OrderedDict(
        model="simulgenvae",
        mode="train",
        gpu_ids="0",
        parallel_mode="single",
        pipeline_log_file="../output/simulgenvae/ex3/full/train.log",
        skip_completed_stages="True",
        output_dir="../output/simulgenvae/ex3/full",
        vae_modelpath="../output/simulgenvae/ex3/full/simulgenvae_vae.pth",
        lc_modelpath="../output/simulgenvae/ex3/full/simulgenvae_lc.pth",
        dataset_dir=TRAIN_DATA,
        split_seed="42",
        num_var="4",
        field_start_row="3",
        cond_var="6",
        node_start="0",
        node_end="0",
        timesteps_reduced="0",
        latent_dim="8",
        latent_dim_end="32",
        num_filter_enc="32 16 8 4",
        network_size="small",
        loss_type="1",
        alpha="1000",
        init_beta_divisor="4",
        vae_training_epochs="2000",
        vae_batch_size="1",
        vae_learningr="0.001",
        vae_weight_decay="0.0",
        vae_warmup_epochs="20",
        vae_log_file_dir="../output/simulgenvae/ex3/full/vae.log",
        lc_filter="32 64 128 256",
        lc_data_type="hdf5",
        lc_dropout="0.2",
        lc_training_epochs="5000",
        lc_batch_size="16",
        lc_learningr="0.001",
        lc_weight_decay="0.00001",
        lc_warmup_epochs="20",
        lc_log_file_dir="../output/simulgenvae/ex3/full/lc.log",
    )
    destination = ROOT / "configs" / "SimulGenVAE" / "ex3" / "config_train.txt"
    return destination, values, "ex3 full-resolution SimulGenVAE VAE-to-latent-conditioner pipeline"


def simulgenvae_reconstruct() -> tuple[Path, OrderedDict[str, str], str]:
    values = OrderedDict(
        model="simulgenvae",
        mode="reconstruct",
        gpu_ids="0",
        dataset_dir=TEST_DATA,
        split_seed="42",
        num_var="4",
        field_start_row="3",
        cond_var="6",
        vae_modelpath="../output/simulgenvae/ex3/full/simulgenvae_vae.pth",
        lc_modelpath="../output/simulgenvae/ex3/full/simulgenvae_lc.pth",
        latent_dim="8",
        latent_dim_end="32",
        num_filter_enc="32 16 8 4",
        lc_filter="32 64 128 256",
        lc_data_type="hdf5",
        batch_size="1",
        output_dir="../output/simulgenvae/ex3/full/reconstruct",
    )
    destination = ROOT / "configs" / "SimulGenVAE" / "ex3" / "config_reconstruct.txt"
    return destination, values, "ex3 full-resolution SimulGenVAE held-out reconstruction"


def main() -> int:
    generated: list[tuple[Path, OrderedDict[str, str], str]] = []
    for mode in ("train", "inference"):
        generated.append(generate_meshgraphnets(hierarchical=False, mode=mode))
        for variant in ("as_is", "p1", "p2", "p12"):
            generated.append(
                generate_meshgraphnets(hierarchical=True, mode=mode, variant=variant)
            )
        for model in ("point_deeponet", "deeponet", "fno", "gino"):
            generated.append(generate_operator(model, mode))
        generated.append(generate_transolver(mode))
    generated.extend((simulgenvae_train(), simulgenvae_reconstruct()))

    for path, values, description in generated:
        write_flat(path, values, description)
        print(path.relative_to(ROOT))
    print(f"generated {len(generated)} configs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
