#!/usr/bin/env bash
# Shared settings. Every script here is run FROM THE AI-CAE4ALL SUITE ROOT after
# install.sh has placed the campaign inside it:
#
#     cd $AICAE_ROOT
#     bash configs/campaigns/iFEM_dense48/prepare.sh
#
# Override PYBIN in the environment if the interpreter differs.
CAMPAIGN="iFEM_dense48"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AICAE_ROOT="${AICAE_ROOT:-$(cd "$HERE/../../.." && pwd)}"
PYBIN="${PYBIN:-/home/sonic/anaconda3/envs/AARL/bin/python}"

DATASET_DIR="$AICAE_ROOT/dataset/$CAMPAIGN"
OUTPUT_DIR="$AICAE_ROOT/output/$CAMPAIGN"

# ARMS_ALL, ARMS_MGN, NUM_GPUS, QUEUE_*, CONFIG_DIR_* -- generated by make_configs.py
source "$HERE/queues.sh"

die() { echo "ERROR: $*" >&2; exit 1; }

config_path() {  # config_path <ARM> <train|infer>
  local arm="$1" mode="$2" var="CONFIG_DIR_$1"
  echo "$AICAE_ROOT/${!var}/config_${mode}_$(echo "$arm" | tr 'A-Z' 'a-z').txt"
}

check_env() {
  [ -x "$PYBIN" ] || die "PYBIN not executable: $PYBIN  (export PYBIN=/path/to/python)"
  [ -f "$AICAE_ROOT/AI_CAE4ALL_main.py" ] || \
    die "not an AI-CAE4ALL checkout: $AICAE_ROOT  (export AICAE_ROOT=...)"
  [ -f "$DATASET_DIR/train.h5" ] || \
    die "missing $DATASET_DIR/train.h5 -- run install.sh from the shipped bundle first"
  [ -f "$(config_path T01 train)" ] || die "configs not installed under $AICAE_ROOT/configs"
}
