#!/usr/bin/env bash
# Launch every GPU queue. Each queue runs its arms sequentially on one device; the queues
# run concurrently so all GPUs stay busy. Detached via setsid+nohup, so they survive logout.
#
# IMPORTANT: Transolver and MeshGraphNets write their checkpoint ONLY after the final epoch
# ("Training interrupted by user. No checkpoint saved." on SIGINT). Interrupting a run
# loses it entirely. Only DeepONet checkpoints periodically (checkpoint_interval 25).
#
#   bash configs/campaigns/iFEM_dense48/train_all.sh          # all queues
#   bash configs/campaigns/iFEM_dense48/train_all.sh 0 2      # only gpu 0 and 2
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
check_env
mkdir -p "$OUTPUT_DIR"

GPUS=${*:-$(seq 0 $((NUM_GPUS - 1)))}
for gpu in $GPUS; do
  eval "queue=\${QUEUE_${gpu}:-}"
  [ -z "$queue" ] && { echo "gpu $gpu: empty queue, skipped"; continue; }

  qlog="$OUTPUT_DIR/queue_gpu${gpu}.log"
  runner="$OUTPUT_DIR/.run_gpu${gpu}.sh"

  # Resolve every path here, in the parent shell, and emit a flat runner with no
  # indirection: what runs days from now is exactly what you can read in this file.
  {
    echo '#!/usr/bin/env bash'
    echo "# generated by train_all.sh -- gpu ${gpu} queue: ${queue}"
    echo "cd '${AICAE_ROOT}' || exit 1"
    for arm in $queue; do
      cfg=$(config_path "$arm" train)
      dir="$OUTPUT_DIR/$arm"
      echo ""
      echo "mkdir -p '${dir}'"
      echo "echo \"[gpu ${gpu}] ${arm} start \$(date -Is)\" >> '${qlog}'"
      echo "'${PYBIN}' -B AI_CAE4ALL_main.py --config '${cfg}' > '${dir}/launcher.log' 2>&1"
      echo "echo \"[gpu ${gpu}] ${arm} exit=\$? \$(date -Is)\" >> '${qlog}'"
    done
    echo ""
    echo "echo \"[gpu ${gpu}] queue finished \$(date -Is)\" >> '${qlog}'"
  } > "$runner"
  chmod +x "$runner"

  echo "gpu $gpu: $queue"
  setsid nohup "$runner" >> "$qlog" 2>&1 &
  echo "  pid $!  log $qlog"
done

echo
echo "progress : tail -f $OUTPUT_DIR/*/train.log"
echo "queues   : cat $OUTPUT_DIR/queue_gpu*.log"
echo "processes: pgrep -af AI_CAE4ALL_main.py"
echo "then     : bash configs/campaigns/$CAMPAIGN/infer_all.sh"
