"""Generate the SAOI FM-v2 production configs -- one recipe, two board halves.

    python configs/MeshGraphNets_Variational/SAOI_sweep/gen_configs.py

This directory used to hold an eight-arm P0->P1->P2->P3 ablation over the flow
matching prior. That campaign is finished and this is its surviving cell.

WHAT THE ABLATION DECIDED (see README.md for the numbers)

P0 -- the untouched baseline -- won `sd_ratio`, `PITtails` and `PIT_KS` in BOTH
halves. Its only loss was `W1/sd`, by under 2%, which is inside single-seed
noise and is driven by conditional-mean accuracy rather than by the width and
calibration this model exists to get right. Widening the velocity MLP from 256
to 512 was the largest replicated effect in the sweep and it was HARMFUL
(sd_ratio -9.5% bot, -29.9% top); residual FiLM was a clean null; the
conditional moment head helped the mean but not the width.

So the winning cell is every FM-v2 key at its native default, and this file
therefore sets none of them -- the twelve-key tail is gone rather than
restated. The defaults that carry the verdict are:

    prior_fm_velocity_arch          mlp     (two-hidden-layer velocity MLP)
    prior_velocity_hidden_dim       = prior_hidden_dim, 256
    prior_fm_moments                False   (global standardization only)
    prior_moment_calibration_epochs 0       (no moment stage)

Everything below is what still has to be SAID, because it differs from the
production profile in SAOI_all_input/ that these are rendered from.
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1] / 'campaigns'))

from sweep_common import write_sweep      # noqa: E402

OUT_ROOT = '../../output/meshgraphnets-v/saoi_fm_v2_sweep'
EPOCHS = '1000'
FREEZE_AT = '700'
TRAINING_SEED = '20260916'

# Named by board half, not by number. The halves are different datasets, not
# variants of one recipe, and `bot.pth` cannot be confused with an arm of the
# retired ablation the way a renumbered `2.pth` could.
ARMS = [
    ('bot', 'bot', {}, 'bottom board half'),
    ('top', 'top', {}, 'top board half'),
]
GPU_OF = {'bot': 0, 'top': 1}

BANNER = """%   ============================================================
%   SAOI MeshGraphNets-V FM-v2 -- {note}
%
%   board half {half}; gpu {gpu}
%
%   FM prior: native defaults (MLP velocity at prior_hidden_dim, no
%   conditional moments). That is the P0 cell of the retired eight-arm
%   ablation, which won sd_ratio, PITtails and PIT_KS in both halves.
%   GENERATED by gen_configs.py; do not hand-edit.
%   ============================================================
"""

INFER_BANNER = """%   ============================================================
%   SAOI FM-v2 inference -- {note}, eval set {tag}; gpu {gpu}.
%
%   `_infer_` supplies graph/thickness/recorded B.C.; `_compare_` supplies the
%   realizations of that same condition, which is what the generated-versus-GT
%   spread histogram is scored against. Each eval set is ONE part with 125
%   realizations, so the histogram's target width ratio is exactly 1.
%   GENERATED by gen_configs.py; do not hand-edit.
%   ============================================================
"""

SPEC = dict(
    here=HERE,
    prod_dir=HERE.parent / 'SAOI_all_input',
    out_root=OUT_ROOT,
    slug='meshgraphnets-v',
    title='MeshGraphNets-V SAOI FM-v2 -- bot and top on one recipe:',
    banner=BANNER,
    infer_banner=INFER_BANNER,
    arms=ARMS,
    gpu_of=lambda arm: GPU_OF[arm],
    infer_sources={
        's26fe_main': 'config_infer_s26fe_main_{half}.txt',
        's26fe_sec':  'config_infer_s26fe_sec_{half}.txt',
        'sm_l345u':   'config_infer_sm_l345u_main_{half}.txt',
    },
    arch_keys=set(),
    train_fixed={
        'Training_epochs': (EPOCHS, 'complete from-scratch schedule'),
        'Batch_size': ('16', 'held fixed across both halves'),
        'training_seed': (TRAINING_SEED,
                          'pinned initialization, shuffle and stochastic latent streams'),
        'split_seed': ('42', 'same 80/10/10 membership in both halves'),
        'prior_freeze_epoch': (
            FREEZE_AT,
            f'freeze encoder/decoder at {FREEZE_AT}; fit only the prior for '
            f'{int(EPOCHS) - int(FREEZE_AT)} epochs on a fresh cosine'),
        'val_interval': ('30', 'CRPS checkpoint-selection interval'),
        'test_interval': ('200', 'periodic visualization interval'),
        'best_by': ('crps', 'select the inference distribution, not posterior reconstruction'),
        'hierarchy_cache_keep': ('True', 'both halves share the hierarchy cache'),
        'recon_loss': ('mse', 'held fixed field reconstruction loss'),
        'alpha_recon': ('1000', 'held fixed reconstruction multiplier'),
        'beta_aux': ('10', 'held fixed decoded peak-to-valley supervision'),
        'prior_grad_to_encoder': (
            '0.0',
            'FM may fit q(z|y,c), but may not shrink the encoder target'),
        'num_vae_samples': ('10000', 'unused during training'),
    },
    infer_fixed={
        'split_seed': (
            '42',
            'MUST match training: the split decides which 80% the normalizers '
            'are fit on, and those denormalize every spread'),
        'num_vae_samples': ('2000', 'stochastic prior draws per condition'),
        'save_rollouts': ('False',
                          'the histogram and spread_values.npz are the record; '
                          'thousands of field files are not'),
        'make_histogram': ('True', 'GT versus generated peak-to-valley distribution'),
        'show_histogram': ('False', 'headless execution'),
        'hierarchy_seed': ('0, 1, 2, 3', 'average over fixed coarsening variants'),
    },
)

if __name__ == '__main__':
    write_sweep(SPEC)
