"""Generate the MeshGraphNets-V SAOI sweep: 8 arms, one per card 0-7.

    python configs/MeshGraphNets_Variational/SAOI_sweep/gen_configs.py

THE AXIS: beta_aux, 0 / 10 / 100 / 1000 on each board section.

    `beta_aux` weights an MSE on the per-graph PEAK-TO-VALLEY of the DECODED
    field -- the statistic the warpage report scores. It replaced a head that
    regressed per-graph [mean, std] from z, which could not move `sd_ratio`
    (0.449-0.526 across the entire previous 8-arm grid) for three structural
    reasons: it read z rather than the decoder output, it used a node-axis
    standard deviation rather than an extreme-value statistic, and at
    beta_aux 1.0 against alpha_recon 1000 it carried ~1% of the objective.

    Four weights spanning three decades, because the natural scale is not
    knowable in advance: with realistic recon/aux magnitudes the weight that
    puts the term at ~30% of the objective came out near 8. Two points could
    not separate "the mechanism fails" from "the weight crushed the
    reconstruction"; a curve can. 0 is the control -- the old head was
    DELETED, so without it nothing separates the new term's effect from that
    removal.

WHY NOTHING ELSE IS SWEPT
    The previous 2^(4-1) grid moved W1/sd by 0.001-0.054 across all four of
    its factors, against a 0.10 arm-to-arm range. z_conditioning,
    prior_grad_to_encoder, capacity and lambda_mmd are not where this model's
    deficit lives, and spending cards on them again would re-measure noise.

BOT AND TOP
    The board's two sections, independent models over one schema. Both carry
    the same ladder, so the curve's SHAPE is replicated rather than fitted
    once -- the previous sweep had no replication at all, which is why its
    factor effects could not support a claim either way.

    The `top` numbers are the weaker half in every previous measurement, so a
    fix that only works on `bot` is not a fix.
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1] / 'campaigns'))

from sweep_common import write_sweep      # noqa: E402

OUT_ROOT = '../../output/meshgraphnets-v/saoi_sweep'
EPOCHS = '1000'

# (arm, section, {key: (value, comment)}, note)
BETAS = ['0', '10', '100', '1000']
NOTE = {
    '0':    'CONTROL: no auxiliary term at all (isolates the deleted head)',
    '10':   'near the balance point estimated from recon/aux magnitudes',
    '100':  'one decade above it',
    '1000': 'at alpha_recon scale -- the strongest the term can reasonably be',
}
ARMS = []
for i, half in enumerate(('bot', 'top')):
    for j, b in enumerate(BETAS):
        ARMS.append((str(i * 4 + j + 1), half,
                     {'beta_aux': (b, NOTE[b])}, NOTE[b]))

BANNER = """%   ============================================================
%   SAOI warpage, MeshGraphNets-V -- arm {arm}
%
%   section   {half}
{axis}
%   gpu {gpu} -- one arm per card, nothing shared
%
%   The axis is beta_aux: an MSE on the DECODED field's peak-to-valley, the
%   statistic the warpage report scores. 0 is the control. Four weights over
%   three decades, because the natural scale is not knowable in advance and
%   two points cannot separate a failed mechanism from a crushed one.
%
%   GENERATED by gen_configs.py from ../SAOI_all_input/config_train_{half}.txt.
%   Do not hand-edit -- regenerate, and change the production profile when a
%   non-swept key needs to move.
%   ============================================================
"""

INFER_BANNER = """%   ============================================================
%   SAOI inference -- arm {arm} ({half}, beta_aux per its train config),
%   eval set {tag}.
%
%   `eval_dataset` is the `_compare_` file: the 125 realizations of the ONE
%   part in `infer_dataset`. That pairing is what makes sd_ratio's target 1 --
%   the truth here IS the conditional distribution, not a single outcome.
%
%   Architecture keys mirror the train config. rollout.py overrides them from
%   checkpoint['model_config'] at load time, so the checkpoint always wins;
%   they are kept in sync so this file documents what runs.
%
%   gpu {gpu}. GENERATED by gen_configs.py -- do not hand-edit.
%   ============================================================
"""

SPEC = dict(
    here=HERE,
    prod_dir=HERE.parent / 'SAOI_all_input',
    out_root=OUT_ROOT,
    slug='meshgraphnets-v',
    title='MeshGraphNets-V SAOI sweep -- beta_aux ladder x 2 sections, one card each:',
    banner=BANNER,
    infer_banner=INFER_BANNER,
    arms=ARMS,
    gpu_of=lambda arm: int(arm) - 1,          # arms 1..8 -> cards 0..7
    infer_sources={
        's26fe_main': 'config_infer_s26fe_main_{half}.txt',
        's26fe_sec':  'config_infer_s26fe_sec_{half}.txt',
        'sm_l345u':   'config_infer_sm_l345u_main_{half}.txt',
    },
    # Keys whose value must be identical in the train and inference configs,
    # or the inference file documents a model the checkpoint is not.
    arch_keys={'beta_aux'},
    train_fixed={
        'Training_epochs': (EPOCHS,
                            'no resume exists and cosine_T0 = epochs - warmup, so '
                            'this is a COMPLETE run at its own schedule; '
                            '~346 s/epoch measured on one card'),
        'Batch_size': ('16', 'the value the previous grid measured as its winner'),
        'val_interval': ('30', 'CRPS is the selection metric'),
        'test_interval': ('200', 'periodic plots; 5 over the run'),
        'best_by': ('crps', 'select on the GENERATIVE metric, not posterior recon'),
        'hierarchy_cache_keep': ('True',
                                 'REQUIRED: every arm shares one cache; a finishing '
                                 'arm must not delete it'),
        'recon_loss': ('mse',
                       'MSE penalizes extreme-node error far more than Huber, which '
                       'caps it -- and peak-to-valley IS an extreme-value statistic'),
        'alpha_recon': ('1000', 'reconstruction multiplier'),
        'num_vae_samples': ('10000', 'draws per scene; unused in train mode'),
        'prior_grad_to_encoder': (
            '0.0',
            'CLOSED for every arm. Open, the FM objective reaches the encoder and '
            'can lower itself by SHRINKING the target distribution (integrated CFM '
            'loss is pi*a/2 for target scale a, so smaller is cheaper even with a '
            'perfectly matched prior). beta_aux is the I(z;y) floor that resists that, '
            'and the CONTROL arm has beta_aux 0 -- nothing would hold its posterior '
            'open, shrinking the control specifically and flattering every other arm. '
            'The previous grid measured this flag at delta 0.001 on W1/sd, so closing '
            'it costs nothing measured'),
    },
    infer_fixed={
        'num_vae_samples': ('2000',
                            'draws per scene. THE DOMINANT COST of this stage: '
                            'arms x eval sets x draws forwards'),
        'save_rollouts': ('False',
                          'one HDF5 per (scene, draw) would be tens of thousands of '
                          'files; the spread values still reach spread_values.npz'),
        'make_histogram': ('True', 'GT vs generated z_disp peak-to-valley'),
        'show_histogram': ('False', 'headless box: save the PNG, do not open a viewer'),
        'hierarchy_seed': ('0, 1, 2, 3',
                           'build one partition per seed and rotate across draw '
                           'batches, so one unlucky partition cannot poison a scene'),
    },
)

if __name__ == '__main__':
    write_sweep(SPEC)
