"""Generate the controlled from-scratch SAOI FM-v2 sweep.

One command writes all training/inference configs:

    python configs/MeshGraphNets_Variational/SAOI_sweep/gen_configs.py

Each board half gets the same four-step ablation. Encoder, decoder, graph
conditioner, data split, RNG seed, optimizer, prior-only tail and inference
budget are held fixed.

    P0  legacy two-hidden-layer FM velocity, width 256
    P1  P0 with velocity width 512                 (capacity only)
    P2  P1 with residual FiLM velocity             (architecture only)
    P3  P2 with conditional mean/scale residuals   (moment base only)

This ordering identifies why an arm improves. The old grid changed tail fit and
graph-trunk capacity together, so it could rank recipes but could not identify
which FM mechanism fixed the conditional distribution.
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1] / 'campaigns'))

from sweep_common import write_sweep      # noqa: E402

OUT_ROOT = '../../output/meshgraphnets-v/saoi_fm_v2_sweep'
EPOCHS = '1000'
FREEZE_AT = '700'
TRAINING_SEED = '20260916'

COMMON_PRIOR = {
    'prior_hidden_dim': ('256', 'backwards-compatible prior width alias'),
    'prior_condition_hidden_dim': ('256', 'HELD FIXED graph conditioner width'),
    'prior_mp_layers': ('5', 'HELD FIXED graph conditioner depth'),
    'prior_fm_blocks': ('4', 'residual block count; ignored by legacy MLP'),
    'prior_fm_moment_hidden_dim': ('256', 'conditional moment-head width'),
    'prior_fm_moment_weight': ('1.0', 'proper Gaussian cross-entropy weight'),
    'prior_fm_moment_min_scale': ('0.03', 'positive diagonal scale floor'),
    'prior_fm_moment_max_scale': ('20.0', 'diagonal scale ceiling'),
}

VARIANTS = (
    ('P0', {
        'prior_velocity_hidden_dim': ('256', 'P0 current FM velocity width'),
        'prior_fm_velocity_arch': ('mlp', 'P0 current two-hidden-layer velocity MLP'),
        'prior_fm_moments': ('False', 'P0 global standardization only'),
        'prior_moment_calibration_epochs': ('0', 'no conditional moment stage'),
    }, 'current FM baseline'),
    ('P1', {
        'prior_velocity_hidden_dim': ('512', 'P1 wider velocity only'),
        'prior_fm_velocity_arch': ('mlp', 'same MLP as P0'),
        'prior_fm_moments': ('False', 'global standardization only'),
        'prior_moment_calibration_epochs': ('0', 'no conditional moment stage'),
    }, 'wider velocity control'),
    ('P2', {
        'prior_velocity_hidden_dim': ('512', 'matched to P1'),
        'prior_fm_velocity_arch': ('residual_film', 'residual velocity with time/condition FiLM'),
        'prior_fm_moments': ('False', 'global standardization only'),
        'prior_moment_calibration_epochs': ('0', 'no conditional moment stage'),
    }, 'residual FiLM FM'),
    ('P3', {
        'prior_velocity_hidden_dim': ('512', 'matched to P1/P2'),
        'prior_fm_velocity_arch': ('residual_film', 'matched to P2'),
        'prior_fm_moments': ('True', 'conditional mean/diagonal scale plus residual FM'),
        'prior_moment_calibration_epochs': (
            '50', 'fit moments on frozen posterior, then freeze base and fit residual FM'),
    }, 'conditional-moment residual FM'),
)

ARMS = []
arm_number = 0
for half in ('bot', 'top'):
    for variant, changes, description in VARIANTS:
        arm_number += 1
        overrides = dict(COMMON_PRIOR)
        overrides.update(changes)
        overrides['fm_variant'] = (variant, f'report label: {description}')
        ARMS.append((str(arm_number), half, overrides,
                     f'{half} {variant}: {description}'))

BANNER = """%   ============================================================
%   SAOI MeshGraphNets-V FM-v2 -- arm {arm} ({note})
%
%   board half {half}
{axis}
%   gpu {gpu}; all arms start from scratch with the same training RNG seed.
%
%   Controlled P0 -> P1 -> P2 -> P3 ablation. Encoder/decoder, graph
%   conditioner, split, optimizer, frozen-prior tail and evaluation are fixed.
%   GENERATED by gen_configs.py; do not hand-edit.
%   ============================================================
"""

INFER_BANNER = """%   ============================================================
%   SAOI FM-v2 inference -- arm {arm} ({note}), eval set {tag}.
%
%   `_infer_` supplies graph/thickness/recorded B.C.; `_compare_` supplies the
%   realizations of that same condition. posterior_vs_prior.py verifies node
%   coordinates, topology, condition rows and configured node/B.C. types.
%   gpu {gpu}. GENERATED by gen_configs.py; do not hand-edit.
%   ============================================================
"""

ARCH_KEYS = {
    'prior_hidden_dim', 'prior_condition_hidden_dim', 'prior_mp_layers',
    'prior_velocity_hidden_dim', 'prior_fm_velocity_arch', 'prior_fm_blocks',
    'prior_fm_moments', 'prior_fm_moment_hidden_dim',
    'prior_fm_moment_weight', 'prior_fm_moment_min_scale',
    'prior_fm_moment_max_scale',
}

SPEC = dict(
    here=HERE,
    prod_dir=HERE.parent / 'SAOI_all_input',
    out_root=OUT_ROOT,
    slug='meshgraphnets-v',
    title='MeshGraphNets-V SAOI FM-v2 sweep -- P0/P1/P2/P3 for bot and top:',
    banner=BANNER,
    infer_banner=INFER_BANNER,
    arms=ARMS,
    gpu_of=lambda arm: int(arm) - 1,
    infer_sources={
        's26fe_main': 'config_infer_s26fe_main_{half}.txt',
        's26fe_sec':  'config_infer_s26fe_sec_{half}.txt',
        'sm_l345u':   'config_infer_sm_l345u_main_{half}.txt',
    },
    arch_keys=ARCH_KEYS,
    train_fixed={
        'Training_epochs': (EPOCHS, 'complete from-scratch schedule'),
        'Batch_size': ('16', 'held fixed across every arm'),
        'training_seed': (TRAINING_SEED,
                          'same initialization, shuffle and stochastic latent streams'),
        'split_seed': ('42', 'same 80/10/10 membership'),
        'prior_freeze_epoch': (
            FREEZE_AT,
            f'freeze encoder/decoder at {FREEZE_AT}; fit only the prior for '
            f'{int(EPOCHS) - int(FREEZE_AT)} epochs on a fresh cosine'),
        'val_interval': ('30', 'CRPS checkpoint-selection interval'),
        'test_interval': ('200', 'periodic visualization interval'),
        'best_by': ('crps', 'select the inference distribution, not posterior reconstruction'),
        'hierarchy_cache_keep': ('True', 'all parallel arms share the hierarchy cache'),
        'recon_loss': ('mse', 'held fixed field reconstruction loss'),
        'alpha_recon': ('1000', 'held fixed reconstruction multiplier'),
        'beta_aux': ('10', 'held fixed decoded peak-to-valley supervision'),
        'prior_grad_to_encoder': (
            '0.0',
            'FM may fit q(z|y,c), but may not shrink the encoder target'),
        'num_vae_samples': ('10000', 'unused during training'),
    },
    infer_fixed={
        'split_seed': (
            '42',
            'MUST match training: posterior_vs_prior.py fits its normalizers on '
            'the train split, so a different seed denormalizes every spread by '
            'the wrong constants'),
        'num_vae_samples': ('2000', 'stochastic prior draws per condition'),
        'save_rollouts': ('False', 'retain statistics without thousands of field files'),
        'make_histogram': ('True', 'GT versus generated peak-to-valley distribution'),
        'show_histogram': ('False', 'headless execution'),
        'hierarchy_seed': ('0, 1, 2, 3', 'average over fixed coarsening variants'),
    },
    det_fixed={
        'num_vae_samples': ('1', 'conditional-centre bias control'),
        'prior_temperature': ('1e-9', 'remove initial sampling noise'),
    },
)

if __name__ == '__main__':
    write_sweep(SPEC)
